insert into config (updatedby,segment,field,value)
values
('Annie','mail','messageToSupportneedImmediate','
{
    "footer": {
        "en": "<div style=\"font-weight:600;\">Why did I get this message?</div><div style=\"padding-top:12px\">Your institution is developing student support services in cooperation with Annie Advisor.<br/> The goal is to provide support for those in need as easily as possible.<br/><br/> The above-mentioned student has request support with a SMS. According to our information they need your support.<br/> If you feel that the matter is not your concern, please answer this email.</div><div style=\"text-align:center;padding-top:40px\"> <img src=\"https://annieadvisor.kinsta.cloud/app/uploads/2022/01/logo.png\" width=\"94\" height=\"54\" alt=\"Annie Advisor logo\"/> </div></div></td><td width=\"10\" style=\"width:10px\"></td></tr></tbody> </table> </td></tr></tbody> </table></div></body></html>",
        "es": "<p>Puedes encontrar las necesidades de apoyo que tus estudiantes han marcardo aquí:<br>https://{{hostname}}.annieadvisor.com</p><p>Si tienes alguna pregunta o duda, contesta a este mensaje :)</p><p>Saludos,<br>Annie</p></body></html>",
        "fi": "<div style=\"font-weight:600;\">Miksi sain tämän viestin?</div><div style=\"padding-top:12px\">Oppilaitoksesi kehittää opiskelijan tukipalveluja yhteistyössä Annie Advisorin kanssa.<br/> Tavoitteena on tehdä tuen saamisesta opiskelijoille mahdollisimman helppoa.<br/><br/> Yllä mainittu opiskelija on pyytänyt tekstiviestillä tukea ja tietojemme mukaan hän tarvitsee sinun tukeasi.<br/> Jos koet, että tämä asia ei kuulu sinulle, voit vastata tähän sähköpostiin.</div><div style=\"text-align:center;padding-top:40px\"> <img src=\"https://annieadvisor.kinsta.cloud/app/uploads/2022/01/logo.png\" width=\"94\" height=\"54\" alt=\"Annie Advisor logo\"/> </div></div></td><td width=\"10\" style=\"width:10px\"></td></tr></tbody> </table> </td></tr></tbody> </table></div></body></html>",
        "sv": "<p>Du kan se listan på stödbehov här:<br>https://{{hostname}}.annieadvisor.com</p><p>Svara på detta meddelande om du har frågor :)</p><p>Mvh,<br>Annie</p></body></html>"
    },
    "header": {
        "en": "<html><body><div style=\"margin:0;padding:0;background-color:#F0F0F7;width:100%;\"> <div style=\"overflow:hidden;color:transparent;width:0;font-size:0;opacity:0;height:0;\"> Hello!{{firstname}} {{lastname}} sent a new message regarding their support need. Proceed to view the support request by clicking the \"Show support request\" -button. </div><table width=\"100%\" height=\"100%\" style=\"min-width:348px\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"> <tbody> <tr height=\"34\" style=\"height:34px\"><td></td></tr><tr align=\"center\"><td> <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"padding-bottom:50px;max-width:650px;min-width:220px\"> <tbody> <tr> <td width=\"10\" style=\"width:10px\"></td><td> <div style=\"border-style:solid;border-width:1px;border-color:#E0E0E0;border-radius:8px;padding-top:30px;padding-bottom:60px;background-color:#FFFFFF\"> <div style=\"font-family:Poppins,Roboto-Regular,Helvetica,Arial,sans-serif;border-bottom:1px solid #E0E0E0;color:#1F2659;padding:0 20px 30px;\"> <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"padding-bottom:12px;\"> <tbody> <tr style=\"line-height:normal;\"> <td> <div style=\"font-size:12px;border:1px solid #FF9650;border-radius:4px;text-transform:uppercase;padding:2px 5px;font-weight:600;background-color:#FF9650;color:#FFFFFF;\">New message</div></td></tr></tbody> </table> <div style=\"font-size:18px;font-weight:600;margin-bottom:5px;\">{{firstname}} {{lastname}} sent a new message</div><div style=\"font-size:14px;font-weight:500;\">View the message and request by clicking hte \"Show support request\" -button</div></div><div style=\"padding-top:50px;text-align:center;\"> <a href=\"https://{{hostname}}.annieadvisor.com/beta/request/{{supportneedid}}\" style=\"text-decoration:none;display:inline-block;font-family:Poppins,Roboto-Regular,Helvetica,Arial,sans-serif;color:#ffffff;font-weight:700;background-color:#027D65;font-size:14px;padding:20px;min-width:250px;border-radius:8px;\"> Show support request </a> </div></div><div style=\"font-family:Poppins,Roboto-Regular,Helvetica,Arial,sans-serif;color:#1F2659;font-size:12px;line-height:18px;text-align:left;padding-top:40px;\">",
        "es": "<html><body><p>¡Hola!</p><p>{{firstname}} {{lastname}} ha enviado un nuevo mensaje sobre sus necesidades de apoyo.</p>",
        "fi": "<html><body><div style=\"margin:0;padding:0;background-color:#F0F0F7;width:100%;\"> <div style=\"overflow:hidden;color:transparent;width:0;font-size:0;opacity:0;height:0;\"> Hei!{{firstname}} {{lastname}} lähetti uuden viestin koskien tukipyyntöään. Siirry katsomaan viestiä painamalla \"Näytä tukipyyntö\" -näppäintä. </div><table width=\"100%\" height=\"100%\" style=\"min-width:348px\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"> <tbody> <tr height=\"34\" style=\"height:34px\"><td></td></tr><tr align=\"center\"><td> <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"padding-bottom:50px;max-width:650px;min-width:220px\"> <tbody> <tr> <td width=\"10\" style=\"width:10px\"></td><td> <div style=\"border-style:solid;border-width:1px;border-color:#E0E0E0;border-radius:8px;padding-top:30px;padding-bottom:60px;background-color:#FFFFFF\"> <div style=\"font-family:Poppins,Roboto-Regular,Helvetica,Arial,sans-serif;border-bottom:1px solid #E0E0E0;color:#1F2659;padding:0 20px 30px;\"> <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"padding-bottom:12px;\"> <tbody> <tr style=\"line-height:normal;\"> <td> <div style=\"font-size:12px;border:1px solid #FF9650;border-radius:4px;text-transform:uppercase;padding:2px 5px;font-weight:600;background-color:#FF9650;color:#FFFFFF;\">Uusi viesti</div></td></tr></tbody> </table> <div style=\"font-size:18px;font-weight:600;margin-bottom:5px;\">{{firstname}} {{lastname}} lähetti viestin</div><div style=\"font-size:14px;font-weight:500;\">Siirry katsomaan viestiä painamalla \"Näytä tukipyyntö\" -näppäintä</div></div><div style=\"padding-top:50px;text-align:center;\"> <a href=\"https://{{hostname}}.annieadvisor.com/beta/request/{{supportneedid}}\" style=\"text-decoration:none;display:inline-block;font-family:Poppins,Roboto-Regular,Helvetica,Arial,sans-serif;color:#ffffff;font-weight:700;background-color:#027D65;font-size:14px;padding:20px;min-width:250px;border-radius:8px;\"> Näytä tukipyyntö </a> </div></div><div style=\"font-family:Poppins,Roboto-Regular,Helvetica,Arial,sans-serif;color:#1F2659;font-size:12px;line-height:18px;text-align:left;padding-top:40px;\">",
        "sv": "<html><body><p>Hej!</p><p>{{firstname}} {{lastname}} skickade ett nyt meddelande angående sitt stödbehov.</p>"
    },
    "subject": {
        "en": "A new message from {{firstname}} {{lastname}}",
        "es": "Un nuevo mensaje de {{firstname}} {{lastname}}",
        "fi": "Uusi viesti opiskelijalta {{firstname}} {{lastname}}",
        "sv": "Nytt meddelande från {{firstname}} {{lastname}}"
    }
}
')
ON CONFLICT (segment,field)
DO UPDATE SET value=EXCLUDED.value, updatedby=EXCLUDED.updatedby, updated=now();
